language: node_js
node_js:
  - "stable"
before_script:
  - npm install
script:
  - npm run build
cache: npm
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
